#pragma once

#include "../resource.hpp"

enum Status {
	SUCCESS,
	FAILED_INIT_FREETYPE,
	FAILED_LOAD_FONT,
	SHADER_NOT_SET,
        FAILED_LOAD_IMAGE,
        EMPTY_BUFFER,

        FAILED_LOADING_SHADER,
        FAILED_COMPILING_SHADER,
        FAILED_COMPILING_VERTEX,
        FAILED_COMPILING_FRAGMENT,
        FAILED_COMPILING_GEOMETRY,
        FAILED_COMPILING_TESSCONTROL,
        FAILED_COMPILING_TESSEVAL,
        FAILED_LINKING_SHADER,
        FAILED_COMPILING_PROGRAM
};